ci : PJTDEV-298 REMOTE 2.7 CI/CD 젠킨스 파일 작성
- 티켓 제거.
- 태그 이외의 branch build 시 tar파일 생성 안함.

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -2,125 +2,76 @@ pipeline {
     agent any
     environment {
         COMMIT = "${GIT_COMMIT.substring(0,7)}"
-        BRANCH_NAME = "${BRANCH_NAME.toLowerCase().trim().split("/")[0]}"
-        JOB_NAME = "${JOB_NAME.split("/")[0].toLowerCase().trim()}"
-        REPO_NAME = sh(returnStdout: true, script: 'git config --get remote.origin.url | rev | cut -f 1 -d "/" | rev | sed "s/.git//gi";sed "/^ *$/d"').toLowerCase().trim() 
+        BRANCH = "${BRANCH_NAME.toLowerCase().trim().split("/")[0]}"
+        JOB = "${JOB_NAME.split("/")[0].toLowerCase().trim()}"
+        REPO_NAME = sh(returnStdout: true, script: 'git config --get remote.origin.url | rev | cut -f 1 -d "/" | rev | sed "s/.git//gi";sed "/^ *$/d"').toLowerCase().trim()
         SLACK_CHANNEL = '#project-dev-jenkins'
         AUTHOR = sh(returnStdout: true, script : 'git --no-pager show -s --pretty="format: %an"')
-        RELATED_TO_PJTDEV= sh( script : 'git --no-pager show  -s --format=%B | grep -i PJTDEV', returnStatus: true)
-        RELATED_TO_SOLUTION= sh( script : 'git --no-pager show -s --format=%B | grep -i SOLUTION', returnStatus: true)
         DIR_PATH = "/data/custom/projectdev-base-2.7/minio/onpremise-tar-files"
-        TICKET = sh(returnStdout:true, script: ' git --no-pager show -s  --pretty="format: %B" | head -1 | cut -f 2 -d : |cut -c 1-12').trim()
-        TAG_EXIST=sh(script: "git tag | grep ${BRANCH_NAME}" , returnStatus: true)
+        TAG_EXIST=sh(script: "git tag | grep ${BRANCH}" , returnStatus: true)
     }
     stages {
         stage ('start') {
             steps {
-                echo "TICKET ::: " + env.TICKET
-                echo "RELATED_TO_PJTDEV :::" + env.RELATED_TO_PJTDEV
-                slackSend (channel: env.SLACK_CHANNEL, color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]' \n AUTHOR: ${env.AUTHOR} \n Build URL: ${env.BUILD_URL}")
+                slackSend (channel: env.SLACK_CHANNEL, color: '#FFFF00', message: "STARTED: Job '${env.JOB}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]' \n AUTHOR: ${env.AUTHOR} \n Build URL: ${env.BUILD_URL}")
             }
         }
-        stage('PJTDEV'){
+        stage('default build'){
             when{
-                expression {    
-                    return RELATED_TO_PJTDEV == "0" 
+                expression {
+                    return TAG_EXIST != "0"
                 }
-            }
-            environment {
-                STAGE_VALUE = "PJTDEV"
-                DOCKER_SAVE_DIR_EXIST =sh(script: "find ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TICKET}/", returnStatus: true)
             }
             steps {
-                sh 'docker build --no-cache -t ${BRANCH_NAME}:${JOB_NAME} -f docker/Dockerfile .'
-                script{
-                    if (env.DOCKER_SAVE_DIR_EXIST == '0'){ 
-                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TICKET}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
-                        echo "docker save success. "
-                    }else{
-                        echo " 디렉토리를 찾을 수 없습니다. "
-                        sh 'mkdir -p ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TICKET}/'
-                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TICKET}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
-                    }
+                sh 'docker build --no-cache -t ${BRANCH}:${JOB} -f docker/Dockerfile .'
                 }
             }
-        }
-        stage ('SOLUTION'){
-            when {
-                expression {    
-                    return RELATED_TO_SOLUTION == "0" && TICKET != "9"
-              }
-            }
-             environment {
-                STAGE_VALUE = "SOLUTION"
-                DOCKER_SAVE_DIR_EXIST =sh(script: "find ${DIR_PATH}/${JOB_NAME}/${TICKET}/${BRANCH_NAME}", returnStatus: true)   
-             }
-            steps{
-                sh 'docker build --no-cache -t ${BRANCH_NAME}:${JOB_NAME} -f docker/Dockerfile .'
-                script{
-                    if (env.DOCKER_SAVE_DIR_EXIST == '0'){
-                       
-                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${TICKET}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
-                        echo "docker save success. "
-                    }else{
-                        echo " 디렉토리를 찾을 수 없습니다. "
-                        sh 'mkdir -p ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${TICKET}/'
-                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${TICKET}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
-                    }
-                }             
-            }
-            post{
-                success{
-                     slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "Docker Build Successful \n tar -  https://192.168.0.9:9000/minio/onpremise-tar-files/${env.STAGE_VALUE}/${env.JOB_NAME}/${env.TICKET}/${env.BRANCH_NAME}.tar " )
-                }
-            }
-        }
         stage('RELEASE'){
             when{
-                expression {    
-                    return TAG_EXIST == "0" 
+                expression {
+                    return TAG_EXIST == "0"
                 }
             }
             environment {
                 STAGE_VALUE = "RELEASE"
-                TAG = sh(returnStdout: true, script:'git describe --tags --abbrev=0 | grep ${BRANCH_NAME} | sed "s/${BRANCH_NAME}//gi"').trim()
-                DOCKER_SAVE_DIR_EXIST =sh(script: "find ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TAG}/", returnStatus: true)
+                TAG = "${env.BRANCH_NAME.toLowerCase().split("/")[1]}"
+                DOCKER_SAVE_DIR_EXIST =sh(script: "find ${DIR_PATH}/${STAGE_VALUE}/${JOB}/${BRANCH}/${TAG}/", returnStatus: true)
             }
             steps {
-                sh 'docker build --no-cache -t ${BRANCH_NAME}:${JOB_NAME} -f docker/Dockerfile .'
+                sh 'docker build --no-cache -t ${BRANCH}:${JOB} -f docker/Dockerfile .'
+                sh 'docker tag ${BRANCH}:${JOB} ${BRANCH}'
                 script{
-                    if (env.TAG_EXIST){
-                        if (env.DOCKER_SAVE_DIR_EXIST == '0'){ 
-                            sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TAG}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
-                            echo "docker save success. "
-                        }else{
-                            echo " 디렉토리를 찾을 수 없습니다. "
-                            sh 'mkdir -p ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TAG}/'
-                            sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TAG}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
-                        }
+                    if (env.DOCKER_SAVE_DIR_EXIST == '0'){
+                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB}/${BRANCH}/${TAG}/${BRANCH}.tar ${BRANCH}'
+                        echo "docker save success. "
+                    }else{
+                        echo " 디렉토리를 찾을 수 없습니다. "
+                        sh 'mkdir -p ${DIR_PATH}/${STAGE_VALUE}/${JOB}/${BRANCH}/${TAG}/'
+                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB}/${BRANCH}/${TAG}/${BRANCH}.tar ${BRANCH}'
+                        echo "docker save success. "
                     }
                 }
             }
             post {
                 success{
-                    slackSend (channel: env.SLACK_CHANNEL, color: 'yello', message: "Docker Build Successful \n tar -  https://192.168.0.9:9000/onpremise-tar-files/${env.STAGE_VALUE}/${env.JOB_NAME}/${env.BRANCH_NAME}/${env.TAG}/${env.BRANCH_NAME}.tar" )
+                    slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "Docker Build Successful \n tar -  https://192.168.0.9:9000/onpremise-tar-files/${env.STAGE_VALUE}/${env.JOB}/${env.BRANCH}/${env.TAG}/${env.BRANCH}.tar" )
                 }
             }
         }
         stage('Deploy'){
             steps {
-                sh 'docker ps -f name=${JOB_NAME}-${BRANCH_NAME} -q  || true  docker stop ${JOB_NAME}-${BRANCH_NAME}'
-                sh 'docker container ls -a -f name=${JOB_NAME}-${BRANCH_NAME} -q || true  docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml rm -f ${JOB_NAME}-${BRANCH_NAME}'
-                sh 'docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml up -d ${BRANCH_NAME}'
+                sh 'docker ps -f name=${JOB}-${BRANCH} -q  || true  docker stop ${JOB}-${BRANCH}'
+                sh 'docker container ls -a -f name=${JOB}-${BRANCH} -q || true  docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml rm -f ${JOB}-${BRANCH}'
+                sh 'docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml up -d ${BRANCH}'
             }
         }
     }
     post {
         success {
-            slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "SUCCESSFUL: ${env.JOB_NAME}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n AUTHOR: ${env.AUTHOR}  \n Build URL: - ${env.BUILD_URL} " )
+            slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "SUCCESSFUL: ${env.JOB}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n AUTHOR: ${env.AUTHOR}  \n Build URL: - ${env.BUILD_URL} " )
         }
         failure {
-            slackSend (channel: env.SLACK_CHANNEL, color: '#FF0000', message: "FAILED: Job  ${env.JOB_NAME}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n AUTHOR: ${env.AUTHOR} \n Build URL: (${env.BUILD_URL})")
-        }    
+            slackSend (channel: env.SLACK_CHANNEL, color: '#FF0000', message: "FAILED: Job  ${env.JOB}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n AUTHOR: ${env.AUTHOR} \n Build URL: (${env.BUILD_URL})")
+        }
     }
 }
