ci : PJTDEV-298 REMOTE 2.7 CI/CD 젠킨스 파일 작성
- 전체 수정
- MiniO DockerFile 빌드 실패 시 개발 서버의 minio 이미지를 사용 할 수 있게 수정
- 티켓 제거.
- 태그 이외의 branch build 시 tar파일 생성 안함.
- 슬랙 메세지 작성자 추가. 
- tar 저장 디렉토리 패턴 변경.
- tar 파일 다운로드 url 수정.

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -1,72 +1,86 @@
+def MINIO_BUILD_CHECK = { 
+    sh(script :'docker build -t ${BRANCH}:${JOB} -f docker/Dockerfile .' ,
+    returnStatus : true)
+}
+
 pipeline {
     agent any
     environment {
         COMMIT = "${GIT_COMMIT.substring(0,7)}"
-        TAG = "${TAG_NAME}"
-        CHANGE_ID = "${CHANGE_ID}"
-        BRANCH_NAME = "${BRANCH_NAME.toLowerCase().trim()}"
-        JOB_NAME = "${JOB_NAME.split("/")[0].toLowerCase().trim()}"
+        BRANCH = "${BRANCH_NAME.toLowerCase().trim().split("/")[0]}"
+        JOB = "${JOB_NAME.split("/")[0].toLowerCase().trim()}"
         REPO_NAME = sh(returnStdout: true, script: 'git config --get remote.origin.url | rev | cut -f 1 -d "/" | rev | sed "s/.git//gi";sed "/^ *$/d"').toLowerCase().trim() 
-
         SLACK_CHANNEL = '#project-dev-jenkins'
+        AUTHOR = sh(returnStdout: true, script : 'git --no-pager show -s --pretty="format: %an"')
+        DIR_PATH = "/data/custom/projectdev-base-2.7/minio/onpremise-tar-files"
+        TAG_EXIST=sh(script: "git tag | grep ${BRANCH}" , returnStatus: true)
     }
-
     stages {
         stage ('start') {
             steps {
-                slackSend (channel: env.SLACK_CHANNEL, color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
+                slackSend (channel: env.SLACK_CHANNEL, color: '#FFFF00', message: "STARTED: Job '${env.JOB}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]' \n AUTHOR: ${env.AUTHOR} \n Build URL: ${env.BUILD_URL}")
             }
         }
-        stage('Build') {
-            environment {
-                DOCKER_SAVE_DIR_EXIST =sh(script: "find /usr/local/custom/projectdev-base-2.7/data/Minio/onpremise-tar-files/${JOB_NAME}/${BRANCH_NAME}", returnStatus: true)
+        stage('default build'){
+            when{
+                expression {    
+                    return TAG_EXIST != "0" 
+                }
             }
-            steps{
-                echo 'commit : ' + COMMIT 
-                echo 'TAG : ' + TAG 
-                echo 'BRANCH_NAME : ' + BRANCH_NAME
-                echo 'job_name : ' + JOB_NAME
-                echo 'REPO_NAME : ' + REPO_NAME
-
+            steps {
                 script{
-                    def BUILD_CHECK = sh ( 
-                    script :'docker build -t ${BRANCH_NAME}:${JOB_NAME} -f docker/Dockerfile .' ,
-                    returnStatus : true
-                    ) 
-
-                    if (BUILD_CHECK != '0'){
-                        sh 'docker tag ${BRANCH_NAME}:base-2.7 ${BRANCH_NAME}:${JOB_NAME}'
-                    }
-
-                    if (env.DOCKER_SAVE_DIR_EXIST == '0'){
-                        sh 'docker save -o /usr/local/custom/projectdev-base-2.7/data/Minio/onpremise-tar-files/${JOB_NAME}/${BRANCH_NAME}/${BRANCH_NAME}:${JOB_NAME}-${COMMIT}.tar ${BRANCH_NAME}:${JOB_NAME}'
-                        echo "docker save success. "
-                    }else{
-                        echo " 디렉토리를 찾을 수 없습니다. "
-                        sh 'mkdir /usr/local/custom/projectdev-base-2.7/data/Minio/onpremise-tar-files/${JOB_NAME}/${BRANCH_NAME}'
-                        sh 'docker save -o /usr/local/custom/projectdev-base-2.7/data/Minio/onpremise-tar-files/${JOB_NAME}/${BRANCH_NAME}/${BRANCH_NAME}:${JOB_NAME}-${COMMIT}.tar ${BRANCH_NAME}:${JOB_NAME}'
-                        
+                    if (MINIO_BUILD_CHECK != '0'){
+                        sh 'docker tag ${BRANCH}:base-2.7 ${BRANCH}:${JOB}'
                     }
                 }
             }
         }
-        stage('Deploy'){
-            when {
-                branch 'pf-minio'
+        stage('RELEASE'){
+            when{
+                expression {    
+                    return TAG_EXIST == "0" 
+                }
+            }
+            environment {
+                STAGE_VALUE = "RELEASE"
+                TAG = "${env.BRANCH_NAME.toLowerCase().split("/")[1]}"
+                DOCKER_SAVE_DIR_EXIST =sh(script: "find ${DIR_PATH}/${STAGE_VALUE}/${JOB}/${BRANCH}/${TAG}/", returnStatus: true)
             }
             steps {
-                sh 'docker ps -f name=${JOB_NAME}-${BRANCH_NAME} -q  || true  docker stop ${JOB_NAME}-${BRANCH_NAME}'
-                sh 'docker container ls -a -f name=${JOB_NAME}-${BRANCH_NAME} -q || true  docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml rm -f ${JOB_NAME}-${BRANCH_NAME}'
-                sh 'docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml up -d ${BRANCH_NAME}'
+                sh 'docker build --no-cache -t ${BRANCH}:${JOB} -f docker/Dockerfile .'
+                sh 'docker tag ${BRANCH}:${JOB} ${BRANCH}'
+                script{
+                    if (env.DOCKER_SAVE_DIR_EXIST == '0'){ 
+                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB}/${BRANCH}/${TAG}/${BRANCH}.tar ${BRANCH}'
+                        echo "docker save success. "
+                    }else{
+                        echo " 디렉토리를 찾을 수 없습니다. "
+                        sh 'mkdir -p ${DIR_PATH}/${STAGE_VALUE}/${JOB}/${BRANCH}/${TAG}/'
+                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB}/${BRANCH}/${TAG}/${BRANCH}.tar ${BRANCH}'
+                        echo "docker save success. "
+                    }
+                }
+            }
+            post {
+                success{
+                    slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "Docker Build Successful \n tar -  https://192.168.0.9:9000/onpremise-tar-files/${env.STAGE_VALUE}/${env.JOB}/${env.BRANCH}/${env.TAG}/${env.BRANCH}.tar" )
+                }
+            }
+        }
+        stage('Deploy'){
+            steps {
+                sh 'docker ps -f name=${JOB}-${BRANCH} -q  || true  docker stop ${JOB}-${BRANCH}'
+                sh 'docker container ls -a -f name=${JOB}-${BRANCH} -q || true  docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml rm -f ${JOB}-${BRANCH}'
+                sh 'docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml up -d ${BRANCH}'
             }
         }
     }
     post {
         success {
-            slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "SUCCESSFUL: ${env.JOB_NAME}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n [Jenkins Build URL]  - ${env.BUILD_URL} \n tar : https://192.168.0.9:9000/minio/onpremise-tar-files/${JOB_NAME}/${BRANCH_NAME}/" )
+            slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "SUCCESSFUL: ${env.JOB}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n AUTHOR: ${env.AUTHOR}  \n Build URL: - ${env.BUILD_URL} " )
         }
         failure {
-            slackSend (channel: env.SLACK_CHANNEL, color: '#FF0000', message: "FAILED: Job  ${env.JOB_NAME}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}] \n (${env.BUILD_URL})")
+            slackSend (channel: env.SLACK_CHANNEL, color: '#FF0000', message: "FAILED: Job  ${env.JOB}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n AUTHOR: ${env.AUTHOR} \n Build URL: (${env.BUILD_URL})")
         }    
     }
 }
