ci : PJTDEV-298 REMOTE 2.7 CI/CD 젠킨스 파일 작성
- 전체 수정
- coturrn 서버용 Jenkinsfile - docker 디렉토리 루트 변경.
- coturrn DockerFile 빌드 실패 시 개발 서버의 minio 이미지를 사용 할 수 있게 수정
- 빌드 스테이지 분리. ( RELEASE (tag),PJTDEV(프로젝트 개발 센터),SOLUTION ( PM 프로젝트),
- 슬랙 메세지 작성자 추가. 
- tar 저장 디렉토리 패턴 변경.
- tar 파일 다운로드 url 수정.

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -1,45 +1,138 @@
+def COTURN_BUILD_CHECK = { 
+    sh(script :'docker build -t ${BRANCH_NAME}:${JOB_NAME} -f docker/Dockerfile .' ,
+    returnStatus : true)
+}
+
 pipeline {
     agent any
     environment {
-        COMMIT = "${GIT_COMMIT}"
-        TAG = "${TAG_NAME}"
-        TEST = "${CHANGE_ID}"
-      BRANCH_NAME = "${BRANCH_NAME.toLowerCase().trim()}"
-      JOB_NAME = "${JOB_NAME.split("/")[0].toLowerCase().trim()}"
-      REPO_NAME = sh(returnStdout: true, script: 'git config --get remote.origin.url | rev | cut -f 1 -d "/" | rev | sed "s/.git//gi";sed "/^ *$/d"').toLowerCase().trim() 
+        COMMIT = "${GIT_COMMIT.substring(0,7)}"
+        BRANCH_NAME = "${BRANCH_NAME.toLowerCase().trim().split("/")[0]}"
+        JOB_NAME = "${JOB_NAME.split("/")[0].toLowerCase().trim()}"
+        REPO_NAME = sh(returnStdout: true, script: 'git config --get remote.origin.url | rev | cut -f 1 -d "/" | rev | sed "s/.git//gi";sed "/^ *$/d"').toLowerCase().trim() 
+        SLACK_CHANNEL = '#project-dev-jenkins'
+        AUTHOR = sh(returnStdout: true, script : 'git --no-pager show -s --pretty="format: %an"')
+        RELATED_TO_PJTDEV= sh( script : 'git --no-pager show  -s --format=%B | head -1 | grep -i PJTDEV ', returnStatus: true)
+        RELATED_TO_SOLUTION= sh( script : 'git --no-pager show -s --format=%B | head -1 | grep -i SOLUTION ', returnStatus: true)
+        DIR_PATH = "/data/custom/projectdev-base-2.7/minio/onpremise-tar-files"
+        TICKET = sh(returnStdout:true, script: ' git --no-pager show -s  --pretty="format: %B" | head -1 | cut -f 2 -d : |cut -c 1-12').trim()
+        TAG_EXIST=sh(script: "git tag | grep ${BRANCH_NAME}" , returnStatus: true)
     }
-
     stages {
-        stage('Build') {
-            steps{
-                echo 'commit : ' + COMMIT 
-                echo 'TAG : ' + TAG 
-                echo 'TEST :' +TEST
-                echo 'BRANCH_NAME : ' + BRANCH_NAME
-                echo 'job_name : ' + JOB_NAME
-                echo 'REPO_NAME : ' + REPO_NAME
+        stage ('start') {
+            steps {
+                echo "TICKET ::: " + env.TICKET
+                echo "RELATED_TO_PJTDEV :::" + env.RELATED_TO_PJTDEV
+                slackSend (channel: env.SLACK_CHANNEL, color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]' \n AUTHOR: ${env.AUTHOR} \n Build URL: ${env.BUILD_URL}")
+            }
+        }
+        stage('PJTDEV'){
+            when{
+                expression {    
+                    return RELATED_TO_PJTDEV == "0" 
+                }
+            }
+            environment {
+                STAGE_VALUE = "PJTDEV"
+                DOCKER_SAVE_DIR_EXIST =sh(script: "find ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TICKET}/", returnStatus: true)
+            }
+            steps {
                 script{
-                  def BUILD_CHECK = sh ( 
-                    script :'docker build -t ${BRANCH_NAME}:${JOB_NAME} -f coturn/Dockerfile .' ,
-                    returnStatus : true
-                  ) 
-                  echo 'BUILD_CHECK :::' +BUILD_CHECK
+                    if (COTURN_BUILD_CHECK!= '0'){
+                        sh 'docker tag ${BRANCH_NAME}:base-2.7 ${BRANCH_NAME}:${JOB_NAME}'
+                    }   
+                    if (env.DOCKER_SAVE_DIR_EXIST == '0'){ 
+                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TICKET}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
+                        echo "docker save success. "
+                    }else{
+                        echo " 디렉토리를 찾을 수 없습니다. "
+                        sh 'mkdir -p ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TICKET}/'
+                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TICKET}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
+                    }
+                }
+            }
+        }
+        stage ('SOLUTION'){
+            when {
+                expression {    
+                    return RELATED_TO_SOLUTION == "0" && TICKET != "9"
+              }
+            }
+             environment {
+                STAGE_VALUE = "SOLUTION"
+                DOCKER_SAVE_DIR_EXIST =sh(script: "find ${DIR_PATH}/${JOB_NAME}/${TICKET}/${BRANCH_NAME}", returnStatus: true)   
+             }
+            steps{
+                script{
+                    if (COTURN_BUILD_CHECK!= '0'){
+                        sh 'docker tag ${BRANCH_NAME}:base-2.7 ${BRANCH_NAME}:${JOB_NAME}'
+                    }
+                    if (env.DOCKER_SAVE_DIR_EXIST == '0'){
+                       
+                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${TICKET}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
+                        echo "docker save success. "
+                    }else{
+                        echo " 디렉토리를 찾을 수 없습니다. "
+                        sh 'mkdir -p ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${TICKET}/'
+                        sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${TICKET}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
+                    }
+                }             
+            }
+            post{
+                success{
+                     slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "Docker Build Successful \n tar -  https://192.168.0.9:9000/minio/onpremise-tar-files/${env.STAGE_VALUE}/${env.JOB_NAME}/${env.TICKET}/${env.BRANCH_NAME}.tar " )
+                }
+            }
+        }
+        stage('RELEASE'){
+            when{
+                expression {    
+                    return TAG_EXIST == "0" 
+                }
+            }
+            environment {
+                STAGE_VALUE = "RELEASE"
+                TAG = sh(returnStdout: true, script:'git describe --tags --abbrev=0 | grep ${BRANCH_NAME} | sed "s/${BRANCH_NAME}//gi"').trim()
+                DOCKER_SAVE_DIR_EXIST =sh(script: "find ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TAG}/", returnStatus: true)
+            }
+            steps {
+                script{
+                    if (COTURN_BUILD_CHECK!= '0'){
+                        sh 'docker tag ${BRANCH_NAME}:base-2.7 ${BRANCH_NAME}:${JOB_NAME}'
+                    }
 
-                  if (BUILD_CHECK != 0){
-                    sh 'docker tag ${BRANCH_NAME} ${BRANCH_NAME}:${JOB_NAME}'
-                  }
+                    if (env.TAG_EXIST){
+                        if (env.DOCKER_SAVE_DIR_EXIST == '0'){ 
+                            sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TAG}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
+                            echo "docker save success. "
+                        }else{
+                            echo " 디렉토리를 찾을 수 없습니다. "
+                            sh 'mkdir -p ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TAG}/'
+                            sh 'docker save -o ${DIR_PATH}/${STAGE_VALUE}/${JOB_NAME}/${BRANCH_NAME}/${TAG}/${BRANCH_NAME}.tar ${BRANCH_NAME}:${JOB_NAME}'
+                        }
+                    }
+                }
+            }
+            post {
+                success{
+                    slackSend (channel: env.SLACK_CHANNEL, color: 'yello', message: "Docker Build Successful \n tar -  https://192.168.0.9:9000/onpremise-tar-files/${env.STAGE_VALUE}/${env.JOB_NAME}/${env.BRANCH_NAME}/${env.TAG}/${env.BRANCH_NAME}.tar" )
                 }
             }
         }
         stage('Deploy'){
-            when {
-              branch 'rm-coturnserver'
-            }
             steps {
-              sh 'docker ps -f name=${JOB_NAME}-${BRANCH_NAME} -q  || true  docker stop ${JOB_NAME}-${BRANCH_NAME}'
-              sh 'docker container ls -a -f name=${JOB_NAME}-${BRANCH_NAME} -q || true  docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml rm -f ${JOB_NAME}-${BRANCH_NAME}'
-              sh 'docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml up -d ${BRANCH_NAME}'
+                sh 'docker ps -f name=${JOB_NAME}-${BRANCH_NAME} -q  || true  docker stop ${JOB_NAME}-${BRANCH_NAME}'
+                sh 'docker container ls -a -f name=${JOB_NAME}-${BRANCH_NAME} -q || true  docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml rm -f ${JOB_NAME}-${BRANCH_NAME}'
+                sh 'docker-compose -f /usr/local/custom/${REPO_NAME}/docker-compose.yaml up -d ${BRANCH_NAME}'
             }
         }
-    }    
+    }
+    post {
+        success {
+            slackSend (channel: env.SLACK_CHANNEL, color: '#00FF00', message: "SUCCESSFUL: ${env.JOB_NAME}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n AUTHOR: ${env.AUTHOR}  \n Build URL: - ${env.BUILD_URL} " )
+        }
+        failure {
+            slackSend (channel: env.SLACK_CHANNEL, color: '#FF0000', message: "FAILED: Job  ${env.JOB_NAME}-${env.BRANCH_NAME} [${env.BUILD_NUMBER}]\n AUTHOR: ${env.AUTHOR} \n Build URL: (${env.BUILD_URL})")
+        }    
+    }
 }
